// Static checkout copy. Customer names, bank details, amounts and references
// remain the saved values in either language.
export const CHECKOUT_DZ: Record<string, string> = {
  'Home': 'གདོང་ཤོག་',
  'Certified authentic Bhutanese handicrafts dispatched directly from master guilds.': 'ངོ་མ་ཨིན་པའི་ངོས་འཛིན་ཅན་གྱི་འབྲུག་གི་ལག་བཟོའི་ཅ་ཆས་ཚུ་ལག་བཟོ་པའི་ཚོགས་པ་ལས་ཐད་ཀར་བཏངམ་ཨིན།',
  'Standard airmail with tracking (10–18 days)': 'རྗེས་འདེད་དང་བཅས་པའི་གནམ་གྲུའི་འཕྲིན་སྐྱེལ་ (ཉིནམ་ ༡༠–༡༨)',
  'Priority air courier (4–7 business days)': 'མགྱོགས་སྐྱེལ་གནམ་གྲུའི་ཞབས་ཏོག་ (ལཱ་གི་ཉིནམ་ ༤–༧)',
  'Bank of Bhutan (mBoB) Official Account': 'འབྲུག་གི་དངུལ་ཁང་ (mBoB) གཞུང་འབྲེལ་རྩིས་ཁྲ་',
  'Bhutan National Bank (BNB) Official Account': 'འབྲུག་རྒྱལ་ཡོངས་དངུལ་ཁང་ (BNB) གཞུང་འབྲེལ་རྩིས་ཁྲ་',
  'Local Currency: Nu.': 'རྒྱལ་ནང་དངུལ་ཀྲམ་: Nu.',
  'Account Title:': 'རྩིས་ཁྲའི་མིང་:',
  'Account Number:': 'རྩིས་ཁྲའི་ཨང་:',
  'Payment details unavailable': 'དངུལ་སྤྲོད་ཀྱི་བརྡ་དོན་མིན་འདུག།',
  'Mobile / Contact:': 'འགྲུལ་འཕྲིན་ / འབྲེལ་གཏུག་:',
  'Scan mBoB QR Code to Pay': 'དངུལ་སྤྲོད་ནི་ལུ་ mBoB QR ཨང་སྐེན་འབད།',
  'Scan BNB mPay QR Code to Pay': 'དངུལ་སྤྲོད་ནི་ལུ་ BNB mPay QR ཨང་སྐེན་འབད།',
  'mBOB Journal / Reference Number *': 'mBoB དངུལ་བསྒྱུར་གྱི་གཞི་བསྟུན་ཨང་ *',
  'BNB Journal / Reference Number *': 'BNB དངུལ་བསྒྱུར་གྱི་གཞི་བསྟུན་ཨང་ *',
  'Transfer in Nu. via mBOB and enter the transaction reference number from your receipt.': 'mBoB བརྒྱུད་དངུལ་ཀྲམ་བསྒྱུར་ཏེ་ འབྱོར་རྟགས་ནང་ཡོད་པའི་གཞི་བསྟུན་ཨང་བཙུགས།',
  'Transfer in Nu. via BNB / mPay and enter the transaction reference number from your receipt.': 'BNB / mPay བརྒྱུད་དངུལ་ཀྲམ་བསྒྱུར་ཏེ་ འབྱོར་རྟགས་ནང་ཡོད་པའི་གཞི་བསྟུན་ཨང་བཙུགས།',
  'Upload Payment Slip / Screenshot (Optional)': 'དངུལ་སྤྲོད་འབྱོར་རྟགས་ / གསལ་གཞིའི་པར་བཙུགས་ (གདམ་ཁ་)',
  'Cash on Delivery (COD) / Pay upon Arrival': 'ཅ་ཆས་ཐོབ་ད་དངུལ་སྤྲོད་ (COD)',
  'Your order will be packed and dispatched directly by the HAB Secretariat. Payment is collected upon parcel delivery.': 'HAB དྲུང་ཆེའི་ཡིག་ཚང་གིས་ཁྱོད་ཀྱི་ཅ་ཆས་སྒྲིལ་ཏེ་ཐད་ཀར་བཏང་འོང་། ཅ་ཆས་ཐོབ་ད་དངུལ་སྤྲོད་དགོ།',
  'All export permits included': 'ཕྱིར་ཚོང་གནང་བ་ཆ་མཉམ་ཚུད་ཡོད།',
  'and understand organic variations are intrinsic to handcrafted Bhutanese crafts.': 'དེ་ལས་འབྲུག་གི་ལག་བཟོའི་ཅ་ཆས་ཚུ་ནང་རང་བཞིན་གྱི་ཁྱད་པར་ཡོདཔ་ཧ་གོ་ཡོད།',
  'CSO Authenticity Certificate Guaranteed': 'CSO ངོ་མ་ཨིན་པའི་ལག་ཁྱེར་གྱི་ཁག་འབག་',
  'Online card payment is not available yet. Choose mBoB, BNB, bank transfer, or cash on delivery. No card details are collected here.': 'ད་ལྟོ་ཨོན་ལཱའིན་ཤོག་བྱང་གི་དངུལ་སྤྲོད་མི་འཐོབ། mBoB, BNB, དངུལ་ཁང་བརྒྱུད་དངུལ་བསྒྱུར་ ཡང་ན་ཅ་ཆས་ཐོབ་ད་དངུལ་སྤྲོད་གདམ་ཁ་རྐྱབ། ནཱ་ལུ་ཤོག་བྱང་གི་བརྡ་དོན་མི་ལེན།',
  'Shop': 'ཚོང་ཁང་',
  'Basket': 'སླེ་ཀེ་',
  'Secure Checkout': 'ཉེན་སྲུང་ཅན་གྱི་དངུལ་སྤྲོད་',
  'Checkout & Order Placement': 'དངུལ་སྤྲོད་དང་མངགས་ཉོ་',
  'Delivery Information': 'ཅ་ཆས་སྐྱེལ་སྤྲོད་ཀྱི་བརྡ་དོན་',
  'Sign in for faster checkout': 'མགྱོགས་པར་མངགས་ཉོ་འབད་ནི་ལུ་ནང་འཛུལ་འབད།',
  'Recipient Full Name *': 'ལེན་མིའི་མིང་ཆ་ཚང་ *',
  'Email Address *': 'གློག་འཕྲིན་ཁ་བྱང་ *',
  'Mobile Phone Number': 'འགྲུལ་འཕྲིན་ཨང་',
  'Street Address / Building / House *': 'ཁ་བྱང་ / སྒྲིང་ཁྱིམ་ / ཁྱིམ་ཨང་ *',
  'City / Dzongkhag *': 'ཁྲོམ་ / རྫོང་ཁག་ *',
  'Country *': 'རྒྱལ་ཁབ་ *',
  'Shipping Carrier': 'ཅ་ཆས་སྐྱེལ་སྤྲོད་ལས་སྡེ་',
  'Payment Method': 'དངུལ་སྤྲོད་ཐབས་ལམ་',
  'SWIFT Wire': 'SWIFT དངུལ་བསྒྱུར་',
  'Cash on Delivery': 'ཅ་ཆས་ཐོབ་ད་དངུལ་སྤྲོད་',
  'Order Summary': 'མངགས་ཉོའི་བཅུད་དོན་',
  'item': 'ཅ་ཆས་',
  'items': 'ཅ་ཆས་',
  'Subtotal': 'ཅ་ཆས་ཀྱི་བསྡོམས་',
  'Shipping': 'སྐྱེལ་སྤྲོད་',
  'Total Amount': 'དངུལ་བསྡོམས་',
  'FREE': 'རིན་མེད་',
  'Securing your order...': 'ཁྱོད་ཀྱི་མངགས་ཉོ་ཐོ་བཀོད་འབད་དོ་...',
  'Place Certified Order': 'མངགས་ཉོ་འབད་',
  'Terms': 'གནས་ཚིག་',
  'I accept the': 'ང་གིས་ཁས་ལེན་འབད་ཡོད་པ་',
  'Your Basket is Empty': 'ཁྱོད་ཀྱི་སླེ་ཀེ་སྟོངམ་ཨིན།',
  'You have not selected any handcrafted items for checkout yet.': 'ཁྱོད་ཀྱིས་ད་ལྟོ་ཚུན་ལག་བཟོའི་ཅ་ཆས་གདམ་ཁ་མ་རྐྱབ་པས།',
  'Explore Authentic Crafts': 'ལག་བཟོའི་ཅ་ཆས་ངོ་མ་ཚུ་གཟིགས།',
  'Bank transfer — confirmed by HAB after review': 'དངུལ་ཁང་བརྒྱུད་དངུལ་བསྒྱུར་ — HAB གིས་ཞིབ་དཔྱད་འབད་དེ་ངེས་གཏན་བཟོ་འོང་།',
  'Bank details are unavailable. Contact HAB before transferring money.': 'དངུལ་ཁང་གི་བརྡ་དོན་མིན་འདུག། དངུལ་མ་བསྒྱུར་བའི་ཧེ་མ་ HAB ལུ་འབྲེལ་བ་འཐབ།',
  'SWIFT Code:': 'SWIFT ཨང་:',
  'Beneficiary:': 'དངུལ་ལེན་མི་:',
  'Bank:': 'དངུལ་ཁང་:',
  'Account:': 'རྩིས་ཁྲ་ཨང་:',
  'Branch:': 'ཡན་ལག་:',
  'Bank transfer reference (required)': 'དངུལ་བསྒྱུར་གྱི་གཞི་བསྟུན་ཨང་ (དགོཔ་)',
  'Upload bank transfer slip / SWIFT copy (required)': 'དངུལ་བསྒྱུར་གྱི་འབྱོར་རྟགས་ / SWIFT འདྲ་བཤུས་བཙུགས་ (དགོཔ་)',
  'Transfer the order total using your name as the payment description. Enter the bank-issued reference below and upload the slip. HAB will check the deposit and confirm payment before dispatch.': 'དངུལ་སྤྲོད་ཀྱི་འགྲེལ་བཤད་ནང་ཁྱོད་ཀྱི་མིང་བཙུགས་ཏེ་དངུལ་བསྡོམས་བསྒྱུར། འོག་ལུ་དངུལ་ཁང་གི་གཞི་བསྟུན་ཨང་དང་འབྱོར་རྟགས་བཙུགས། HAB གིས་དངུལ་ཞིབ་དཔྱད་འབད་དེ་ཅ་ཆས་མ་བཏང་བའི་ཧེ་མ་ངེས་གཏན་བཟོ་འོང་།',
  'Uploading...': 'བཙུགས་དོ་...',
  '✓ Slip Attached': '✓ འབྱོར་རྟགས་བཙུགས་ཡོད།',
  'Please provide recipient full name.': 'ལེན་མིའི་མིང་ཆ་ཚང་བཙུགས།',
  'Please provide a valid email address for tracking updates.': 'བརྡ་དོན་གསར་པ་ཐོབ་ནི་ལུ་གློག་འཕྲིན་ཁ་བྱང་ངོ་མ་བཙུགས།',
  'Please provide a physical delivery street address.': 'ཅ་ཆས་སྐྱེལ་སྤྲོད་ཀྱི་ཁ་བྱང་བཙུགས།',
  'Please wait until your payment slip finishes uploading.': 'དངུལ་སྤྲོད་འབྱོར་རྟགས་བཙུགས་ཚར་ཚུན་སྒུག་གནང་།',
};

export function checkoutCopy(text: string, language: 'en' | 'dz') {
  return language === 'dz' ? CHECKOUT_DZ[text] || text : text;
}
