// Existing public copy, retained as a read fallback until a section is first edited.
export const STRATEGIC_PILLARS = [
  { num: '01', title: 'Cluster Formalization & Market Access', desc: 'Transitioning 7,500 rural household producers into certified village cooperatives across all 20 Dzongkhags. Equipping clusters with common production sheds, centralized raw material procurement, and direct linkages to domestic outlets and the international e-shop.', metric: '10,000+ Active Artisans by 2030' },
  { num: '02', title: 'Endangered Zorig Chusum Transmission', desc: 'Targeted institutional interventions for endangered traditional arts facing practitioner decline—specifically traditional iron forging (Garo), bronze casting (Lugzo), and slate carving (Doma). Funding long-term paid apprenticeships under Living Master Craftspeople.', metric: '150+ Paid Youth Apprenticeships' },
  { num: '03', title: 'Raw Material Sovereignty & Ecological Nurseries', desc: 'Reducing dependency on imported yarns and synthetic chemicals through community cultivation of wild Daphne barks, indigo, and madder root gardens. Establishing cooperative dye vats and sustainable timber harvesting permits.', metric: '100% Bhutanese Natural Dye Guarantee' },
  { num: '04', title: 'Digital Provenance & Global Direct Exports', desc: 'Scaling our digital provenance registry linking physical Royal Seals of Authenticity to artisan maker cards via QR verification. Expanding streamlined DHL and Bhutan Post EMS international air cargo corridors with zero intermediary tariffs.', metric: 'Worldwide Delivery in 5–7 Working Days' },
  { num: '05', title: 'Female Craft Leadership & Cluster Livelihoods', desc: 'Deepening financial autonomy for the 70%+ women artisans leading our weaving, embroidery, and bamboo basketry sectors through flexible home-based production, equipment micro-grants, and cooperative childcare pilot programs.', metric: 'Nu. 75M+ Annual Direct Female Disbursements' },
];

export const MANDATE_ARTICLES = [
  { num: 'Article I', title: 'Sovereign Heritage & Stewardship of Zorig Chusum', body: 'The Association is constituted as the peak civil society body entrusted with safeguarding, transmitting, and advocating for the thirteen traditional arts and crafts (Zorig Chusum) of the Kingdom of Bhutan, ensuring ancient techniques remain living, thriving economic pursuits rather than museum antiquities.', tags: ['Cultural Continuity', 'Zorig Chusum', 'Crown Heritage'] },
  { num: 'Article II', title: 'Artisan Economic Protection & Elimination of Middlemen', body: 'HAB holds a statutory mandate to eliminate unfair predatory trading by guaranteeing fair upfront purchase prices to rural creators. The Association operates non-profit consignment and direct market infrastructure, ensuring over 84% of turnover flows directly to artisan producers.', tags: ['Fair Trade', '7,500+ Artisans', 'Upfront Payment'] },
  { num: 'Article III', title: 'National Quality Standards & Royal Seal of Origin', body: 'Empowered to inspect, accredit, and certify traditional Bhutanese craft pieces with the official Seal of Authenticity. HAB enforces strict origin traceability to protect local makers against mass-produced counterfeit imports sold under Bhutanese names.', tags: ['Provenance Certification', 'Anti-Counterfeit', 'Origin Traceability'] },
  { num: 'Article IV', title: 'Fiduciary Governance & Public Financial Disclosure', body: 'Under Section 31 of the CSO Act of Bhutan 2007, HAB operates under audited double-entry accounts certified annually by independent Chartered Accountants. No portion of net earnings may inure to any private shareholder or individual trustee.', tags: ['CSO/2011/043', 'Independent Audits', 'Public Ledgers'] },
  { num: 'Article V', title: 'Nationwide Cluster Representation Across 20 Dzongkhags', body: 'The Association shall maintain democratic artisan representation from all twenty Dzongkhags of Bhutan, fostering self-governing village craft clusters, women-led weaving guilds, and youth apprenticeships with equal access to tools and donor interventions.', tags: ['20 Dzongkhags', '70% Women-Led', 'Village Clusters'] },
];

export const ETHICS_STANDARDS = [
  { iconKey: '0', title: 'Upfront Fair Remuneration', body: 'Artisans are paid an agreed fair wholesale rate upon product handover in Thimphu or regional clusters. Payment is strictly never contingent on final retail sale, eliminating inventory risk for grassroots craft families.' },
  { iconKey: '1', title: 'Prohibition of Middlemen & Exploitation', body: 'HAB directly engages producer households and clusters. Intermediary broker fees and unregulated commissions are strictly banned across our e-shop, physical outlets, and donor consignment programs.' },
  { iconKey: '2', title: 'Sacred Iconography & Cultural Reverence', body: 'Traditional religious arts—including consecrated bronze statues, ceremonial wood masks, and sacred thangkas—must adhere strictly to Department of Culture proportions and Buddhist aesthetic canons.' },
  { iconKey: '3', title: 'Gender Parity & Dignified Workspaces', body: 'Over 70% of HAB-affiliated enterprises are women-led. We enforce zero harassment, equal pay, safe ventilation in dyeing/forging facilities, and child-safe home cluster environments.' },
  { iconKey: '4', title: 'Sustainable Ecological Harvesting', body: 'All wild craft materials—including Daphne bark for Desho paper, bamboo cane roots, and plant dyestuffs—must be gathered sustainably in compliance with national community forestry guidelines.' },
  { iconKey: '5', title: 'Zero Tolerance for Counterfeits', body: 'Imported factory goods or machine-embroidered textiles falsely branded as traditional Bhutanese crafts result in immediate revocation of member credentials, store clearance, and CSO statutory referral.' },
];
