import { NextResponse } from 'next/server';
import prisma from '@/lib/prisma';
import { CLIENT_VERBATIM } from '@/lib/data';

export const dynamic = 'force-dynamic';

export async function GET() {
  try {
    let setting = await prisma.siteSetting.findUnique({ where: { id: 'default' } });
    if (!setting) {
      setting = await prisma.siteSetting.create({
        data: {
          id: 'default',
          announcementText: 'CSO/2011/043 · Handicrafts Association of Bhutan · Apex Civil Society Organization',
          announcementLink: '/about',
          isAnnouncementOn: true,
          tagline: CLIENT_VERBATIM.tagline,
          heroParagraph: CLIENT_VERBATIM.heroPara,
          heroCtaPrimaryText: 'Our mission',
          heroCtaPrimaryLink: '/about',
          heroCtaSecondaryText: 'Shop the crafts →',
          heroCtaSecondaryLink: '/shop',
          stat1Number: CLIENT_VERBATIM.stats[0]?.n || '7,500',
          stat1Label: CLIENT_VERBATIM.stats[0]?.label || 'Micro & small enterprises in the network',
          stat2Number: CLIENT_VERBATIM.stats[1]?.n || '5,250',
          stat2Label: CLIENT_VERBATIM.stats[1]?.label || 'Women-led enterprises',
          stat3Number: CLIENT_VERBATIM.stats[2]?.n || '195',
          stat3Label: CLIENT_VERBATIM.stats[2]?.label || 'Affiliated stores across Bhutan',
          stat4Number: CLIENT_VERBATIM.stats[3]?.n || '13',
          stat4Label: CLIENT_VERBATIM.stats[3]?.label || 'Arts & crafts of Zorig Chusum',
          officeAddress: CLIENT_VERBATIM.contactBlock.address,
          officePhone: CLIENT_VERBATIM.contactBlock.office,
          edPhone: CLIENT_VERBATIM.contactBlock.ed,
          marketingPhone: CLIENT_VERBATIM.contactBlock.marketing,
          officialEmail: CLIENT_VERBATIM.contactBlock.email,
          footerAbout: 'Handicrafts Association of Bhutan is the apex civil society organization stewarding Bhutan’s thirteen traditional arts and crafts (Zorig Chusum). We empower rural craftspeople, safeguard indigenous cultural heritage, and open international market access.',
          csoRegistration: 'CSO Registration: CSO/2011/043 · Thimphu, Kingdom of Bhutan',
          copyrightText: '© 2026 Handicrafts Association of Bhutan. All rights reserved.',
          punakhaMarketNotice: CLIENT_VERBATIM.punakhaMarket,
          partnersList: CLIENT_VERBATIM.partners,
          assurance1Title: 'Verified members only',
          assurance1Text: 'Every seller is a registered HAB member with documented craft credentials.',
          assurance2Title: 'Fair price, paid upfront',
          assurance2Text: 'HAB buys from the artisan at an agreed price before the piece is listed.',
          assurance3Title: 'Secure payment',
          assurance3Text: '3-D Secure cards, mBoB and bank transfer, in USD or Ngultrum.',
          assurance4Title: 'Tracked worldwide',
          assurance4Text: 'EMS via Bhutan Post with commercial invoice and craft certificate.',
          aboutBandTitle: 'A network built for the artisans, not the middlemen',
          aboutBandPara1: 'Handicrafts Association of Bhutan (HAB) plays a critical role in the Bhutanese handicrafts sector. We work towards creating a vibrant, sustainable, and inclusive craft ecosystem by bridging traditional techniques with modern markets, and ensuring fair compensation for our artisans.',
          aboutBandPara2: 'Our nationwide network supports more than 7,500 micro and small craft enterprises — 70% women-led — across all twenty dzongkhags. We provide capacity building, quality certification, and direct market access through our physical outlets and international e-shop.',
          aboutBandImageUrl: '/images/training_workshop.jpg',
          aboutBandImageCaption: 'HAB artisan training workshop · Thimphu',
          aboutBandCtaText: 'Read about our programmes →',
          aboutBandCtaLink: '/programmes',
          membershipLeftTitle: 'Find a member',
          membershipLeftText: 'Connect directly with master craftspeople, verified weaving clusters, and traditional workshops across Bhutan.',
          membershipLeftCtaText: 'Search member directory →',
          membershipLeftCtaLink: '/members',
          membershipRightTitle: 'Become a member',
          membershipRightText: 'Access product consignment in our central shop, participate in donor training programmes, and represent your craft in international trade fairs.',
          membershipRightCtaText: 'Apply for membership',
          membershipRightCtaLink: '/membership/apply',
        },
      });
    }
    return NextResponse.json({ success: true, setting });
  } catch (error) {
    return NextResponse.json({
      success: true,
      setting: {
        announcementText: 'CSO/2011/043 · Handicrafts Association of Bhutan',
        announcementLink: '/about',
        isAnnouncementOn: true,
        tagline: CLIENT_VERBATIM.tagline,
        heroParagraph: CLIENT_VERBATIM.heroPara,
        heroCtaPrimaryText: 'Our mission',
        heroCtaPrimaryLink: '/about',
        heroCtaSecondaryText: 'Shop the crafts →',
        heroCtaSecondaryLink: '/shop',
        stat1Number: '7,500',
        stat1Label: 'Micro & small enterprises in the network',
        stat2Number: '5,250',
        stat2Label: 'Women-led enterprises',
        stat3Number: '195',
        stat3Label: 'Affiliated stores across Bhutan',
        stat4Number: '13',
        stat4Label: 'Arts & crafts of Zorig Chusum',
        officeAddress: CLIENT_VERBATIM.contactBlock.address,
        officePhone: CLIENT_VERBATIM.contactBlock.office,
        edPhone: CLIENT_VERBATIM.contactBlock.ed,
        marketingPhone: CLIENT_VERBATIM.contactBlock.marketing,
        officialEmail: CLIENT_VERBATIM.contactBlock.email,
        footerAbout: 'Handicrafts Association of Bhutan is the apex civil society organization stewarding Bhutan’s traditional crafts.',
        csoRegistration: 'CSO Registration: CSO/2011/043 · Thimphu, Kingdom of Bhutan',
        copyrightText: '© 2026 Handicrafts Association of Bhutan. All rights reserved.',
        punakhaMarketNotice: CLIENT_VERBATIM.punakhaMarket,
        partnersList: CLIENT_VERBATIM.partners,
        assurance1Title: 'Verified members only',
        assurance1Text: 'Every seller is a registered HAB member with documented craft credentials.',
        assurance2Title: 'Fair price, paid upfront',
        assurance2Text: 'HAB buys from the artisan at an agreed price before the piece is listed.',
        assurance3Title: 'Secure payment',
        assurance3Text: '3-D Secure cards, mBoB and bank transfer, in USD or Ngultrum.',
        assurance4Title: 'Tracked worldwide',
        assurance4Text: 'EMS via Bhutan Post with commercial invoice and craft certificate.',
        aboutBandTitle: 'A network built for the artisans, not the middlemen',
        aboutBandPara1: 'Handicrafts Association of Bhutan (HAB) plays a critical role in the Bhutanese handicrafts sector. We work towards creating a vibrant, sustainable, and inclusive craft ecosystem by bridging traditional techniques with modern markets, and ensuring fair compensation for our artisans.',
        aboutBandPara2: 'Our nationwide network supports more than 7,500 micro and small craft enterprises — 70% women-led — across all twenty dzongkhags. We provide capacity building, quality certification, and direct market access through our physical outlets and international e-shop.',
        aboutBandImageUrl: '/images/training_workshop.jpg',
        aboutBandImageCaption: 'HAB artisan training workshop · Thimphu',
        aboutBandCtaText: 'Read about our programmes →',
        aboutBandCtaLink: '/programmes',
        membershipLeftTitle: 'Find a member',
        membershipLeftText: 'Connect directly with master craftspeople, verified weaving clusters, and traditional workshops across Bhutan.',
        membershipLeftCtaText: 'Search member directory →',
        membershipLeftCtaLink: '/members',
        membershipRightTitle: 'Become a member',
        membershipRightText: 'Access product consignment in our central shop, participate in donor training programmes, and represent your craft in international trade fairs.',
        membershipRightCtaText: 'Apply for membership',
        membershipRightCtaLink: '/membership/apply',
      },
    });
  }
}